<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DefaultItemExcludes>$(DefaultItemExcludes);temp\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Icons\AppIcon.png" />
    <None Remove="Assets\Icons\Close.svg" />
    <None Remove="Assets\Icons\Pause.svg" />
    <None Remove="Assets\Icons\Play.svg" />
    <None Remove="Assets\Icons\Refresh.svg" />
    <None Remove="Assets\Icons\Record.svg" />
    <None Remove="Assets\Icons\Settings.svg" />
    <Resource Include="Assets\Icons\AppIcon.png" />
    <Resource Include="Assets\Icons\Close.svg" />
    <Resource Include="Assets\Icons\Pause.svg" />
    <Resource Include="Assets\Icons\Play.svg" />
    <Resource Include="Assets\Icons\Refresh.svg" />
    <Resource Include="Assets\Icons\Record.svg" />
    <Resource Include="Assets\Icons\Settings.svg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Sounds\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
